version: '3'

services:
  ci-build:
    image: microsoft/aspnetcore-build:latest
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore ./DevOpsHackSimpleProject.sln && dotnet publish ./DevOpsHackSimpleProject.sln -c Release -o ./obj/Docker/publish"
